"""Bootstrap a :class:`OpenCOATRuntime` against an OpenClaw-shaped event bus.

Generated by ``opencoat plugin install openclaw`` (post-M5 DX sprint).

Wires:

* an in-process :class:`OpenCOATRuntime` with memory stores + stub LLM,
* the M5 :class:`OpenClawAdapter` + :class:`OpenClawMemoryBridge`,
* lifecycle hooks via :func:`install_hooks`.

Replace :class:`StubLLMClient` with a real one and edit
:mod:`concerns` to make this useful.
"""

from __future__ import annotations

from opencoat_runtime_core import OpenCOATRuntime, RuntimeConfig
from opencoat_runtime_core.llm import StubLLMClient
from opencoat_runtime_host_openclaw import (
    InstalledHooks,
    OpenClawAdapter,
    OpenClawHost,
    OpenClawMemoryBridge,
    install_hooks,
)
from opencoat_runtime_storage.memory import MemoryConcernStore, MemoryDCNStore

from .concerns import seed_concerns

DEFAULT_EVENT_NAMES: tuple[str, ...] = (
    "agent.started",
    "agent.user_message",
    "agent.memory_write",
)


def build_runtime() -> OpenCOATRuntime:
    return OpenCOATRuntime(
        RuntimeConfig(),
        concern_store=MemoryConcernStore(),
        dcn_store=MemoryDCNStore(),
        llm=StubLLMClient(),
    )


def seed_stores(runtime: OpenCOATRuntime) -> None:
    for concern in seed_concerns():
        runtime.concern_store.upsert(concern)
        runtime.dcn_store.add_node(concern)


def install(
    host: OpenClawHost,
    *,
    event_names: tuple[str, ...] = DEFAULT_EVENT_NAMES,
) -> tuple[OpenCOATRuntime, InstalledHooks]:
    """Build runtime, seed stores, install hooks. Caller must ``.uninstall()``."""
    runtime = build_runtime()
    seed_stores(runtime)
    installed = install_hooks(
        host,
        runtime=runtime,
        adapter=OpenClawAdapter(),
        bridge=OpenClawMemoryBridge(dcn_store=runtime.dcn_store),
        event_names=event_names,
    )
    return runtime, installed


__all__ = ["DEFAULT_EVENT_NAMES", "build_runtime", "install", "seed_stores"]
