"""Hand-authored concerns for the OpenClaw plugin scaffold.

Generated by ``COATr plugin install openclaw`` (post-M5 DX sprint).

Each concern below demonstrates a different ``AdviceType`` /
``WeavingLevel`` pair so the scaffold lights up multiple injection
paths the first time you run it. Edit / extend / replace freely.
"""

from __future__ import annotations

from COAT_runtime_protocol import (
    Advice,
    AdviceType,
    Concern,
    Pointcut,
    WeavingLevel,
    WeavingOperation,
    WeavingPolicy,
)
from COAT_runtime_protocol.envelopes import PointcutMatch


def _coat_prompt_prefix() -> Concern:
    return Concern(
        id="c-openclaw-prompt-prefix",
        name="OpenClaw scaffold — system prompt prefix",
        description="Prepend a small policy line to the system prompt.",
        pointcut=Pointcut(joinpoints=["on_request_received"]),
        advice=Advice(
            type=AdviceType.RESPONSE_REQUIREMENT,
            content="You are running under the COAT runtime. Be concise.",
        ),
        weaving_policy=WeavingPolicy(
            mode=WeavingOperation.INSERT,
            level=WeavingLevel.PROMPT_LEVEL,
            target="runtime_prompt.system_prefix",
            priority=0.5,
        ),
    )


def _coat_memory_note() -> Concern:
    return Concern(
        id="c-openclaw-memory-note",
        name="OpenClaw scaffold — memory write note",
        description="Annotate memory writes with a lightweight policy hint.",
        pointcut=Pointcut(joinpoints=["before_memory_write"]),
        advice=Advice(
            type=AdviceType.MEMORY_WRITE_GUARD,
            content="Memory writes are mirrored to the DCN via OpenClawMemoryBridge.",
        ),
        weaving_policy=WeavingPolicy(
            mode=WeavingOperation.INSERT,
            level=WeavingLevel.MEMORY_LEVEL,
            target="memory_write.policy_note",
            priority=0.5,
        ),
    )


def _coat_user_keyword() -> Concern:
    return Concern(
        id="c-openclaw-user-coat",
        name="OpenClaw scaffold — COAT mention",
        description="Add a runtime hint when the user mentions COAT.",
        pointcut=Pointcut(
            joinpoints=["on_user_input"],
            match=PointcutMatch(any_keywords=["COAT", "coat"]),
        ),
        advice=Advice(
            type=AdviceType.REASONING_GUIDANCE,
            content="Acknowledge the COAT runtime in one sentence before answering.",
        ),
        weaving_policy=WeavingPolicy(
            mode=WeavingOperation.INSERT,
            level=WeavingLevel.PROMPT_LEVEL,
            target="runtime_prompt.reasoning_guidance",
            priority=0.6,
        ),
    )


def seed_concerns() -> list[Concern]:
    return [_coat_prompt_prefix(), _coat_memory_note(), _coat_user_keyword()]


__all__ = ["seed_concerns"]
