"""Hand-authored concerns for the custom plugin scaffold.

Generated by ``opencoat plugin install custom`` (post-M5 DX sprint).
"""

from __future__ import annotations

from opencoat_runtime_protocol import (
    Advice,
    AdviceType,
    Concern,
    Pointcut,
    WeavingLevel,
    WeavingOperation,
    WeavingPolicy,
)


def _opencoat_demo() -> Concern:
    return Concern(
        id="c-custom-demo",
        name="Custom scaffold — demo concern",
        description=(
            "Trivial concern proving the wiring works end-to-end. "
            "``on_user_input`` is a built-in joinpoint in the OpenCOAT "
            "catalog; your adapter's ``map_host_event`` must emit it "
            "for this concern to fire."
        ),
        pointcut=Pointcut(joinpoints=["on_user_input"]),
        advice=Advice(
            type=AdviceType.RESPONSE_REQUIREMENT,
            content="Acknowledge the OpenCOAT runtime is active.",
        ),
        weaving_policy=WeavingPolicy(
            mode=WeavingOperation.INSERT,
            level=WeavingLevel.PROMPT_LEVEL,
            target="runtime_prompt.active_concerns",
            priority=0.5,
        ),
    )


def seed_concerns() -> list[Concern]:
    return [_opencoat_demo()]


__all__ = ["seed_concerns"]
