"""Skeleton :class:`HostAdapter` for a bespoke agent framework.

Generated by ``COATr plugin install custom`` (post-M5 DX sprint).

Fill in :meth:`map_host_event` and :meth:`apply_injection` — see
``opencoat_runtime_host_openclaw.adapter`` for a fully-worked reference.
"""

from __future__ import annotations

from collections.abc import Iterable

from opencoat_runtime_core.ports import HostAdapter
from opencoat_runtime_protocol import ConcernInjection, JoinpointEvent


class CustomHostAdapter(HostAdapter):
    """Translate a custom host's events into JoinpointEvents (and back)."""

    def __init__(self, host_name: str = "custom") -> None:
        self._host_name = host_name

    @property
    def host_name(self) -> str:
        return self._host_name

    def map_host_event(self, event: dict) -> JoinpointEvent | None:
        # Inspect ``event``, return a JoinpointEvent for events you want
        # the runtime to react to. Return ``None`` to ignore.
        raise NotImplementedError("Override map_host_event for your framework.")

    def map_host_events(self, events: Iterable[dict]) -> Iterable[JoinpointEvent]:
        for event in events:
            jp = self.map_host_event(event)
            if jp is not None:
                yield jp

    def apply_injection(self, injection: ConcernInjection, host_context: dict) -> dict:
        # Fold ``injection.injections`` back into ``host_context`` —
        # see OpenClawInjector for a path-based merge implementation.
        raise NotImplementedError("Override apply_injection for your framework.")


__all__ = ["CustomHostAdapter"]
