"""Bootstrap a :class:`COATRuntime` for a user-defined host.

Generated by ``COATr plugin install custom`` (post-M5 DX sprint).

Wires an in-process :class:`COATRuntime` with memory stores + stub LLM
and a :class:`CustomHostAdapter` (see :mod:`host_adapter`). You are
responsible for driving the adapter from your own agent loop:

* call ``adapter.map_host_event(event)`` for each event you observe,
* call ``adapter.apply_injection(injection, host_context)`` to fold
  the runtime's advice back into your context.
"""

from __future__ import annotations

from COAT_runtime_core import COATRuntime, RuntimeConfig
from COAT_runtime_core.llm import StubLLMClient
from COAT_runtime_storage.memory import MemoryConcernStore, MemoryDCNStore

from .concerns import seed_concerns
from .host_adapter import CustomHostAdapter


def build_runtime() -> COATRuntime:
    return COATRuntime(
        RuntimeConfig(),
        concern_store=MemoryConcernStore(),
        dcn_store=MemoryDCNStore(),
        llm=StubLLMClient(),
    )


def seed_stores(runtime: COATRuntime) -> None:
    for concern in seed_concerns():
        runtime.concern_store.upsert(concern)
        runtime.dcn_store.add_node(concern)


def build_runtime_with_adapter(
    host_name: str = "custom",
) -> tuple[COATRuntime, CustomHostAdapter]:
    """Convenience helper for the common in-process wiring."""
    runtime = build_runtime()
    seed_stores(runtime)
    return runtime, CustomHostAdapter(host_name=host_name)


__all__ = ["build_runtime", "build_runtime_with_adapter", "seed_stores"]
