"""Hand-authored concerns for the custom plugin scaffold.

Generated by ``COATr plugin install custom`` (post-M5 DX sprint).
"""

from __future__ import annotations

from COAT_runtime_protocol import (
    Advice,
    AdviceType,
    Concern,
    Pointcut,
    WeavingLevel,
    WeavingOperation,
    WeavingPolicy,
)


def _coat_demo() -> Concern:
    return Concern(
        id="c-custom-demo",
        name="Custom scaffold — demo concern",
        description="Trivial concern proving the wiring works end-to-end.",
        pointcut=Pointcut(joinpoints=["on_request_received"]),
        advice=Advice(
            type=AdviceType.RESPONSE_REQUIREMENT,
            content="Acknowledge the COAT runtime is active.",
        ),
        weaving_policy=WeavingPolicy(
            mode=WeavingOperation.INSERT,
            level=WeavingLevel.PROMPT_LEVEL,
            target="runtime_prompt.system_prefix",
            priority=0.5,
        ),
    )


def seed_concerns() -> list[Concern]:
    return [_coat_demo()]


__all__ = ["seed_concerns"]
