"""Bootstrap OpenClaw against the OpenCOAT runtime.

Generated by ``opencoat plugin install openclaw``.

Two install paths are exposed; pick the one that matches your topology:

* :func:`install` — **daemon-backed** (default). Connects to a long-
  running OpenCOAT daemon over HTTP JSON-RPC. Pair with::

      opencoat runtime up
      opencoat concern import --demo        # or your own concerns

  Concerns + DCN state live in the daemon, so ``opencoat concern …``
  / ``opencoat dcn …`` show the same picture the running host agent
  reacts to. This is the topology the ``opencoat-skill`` demo flow
  assumes.

* :func:`install_in_process` — embedded runtime, memory stores, stub
  LLM. No daemon needed. Useful for unit tests or single-shot scripts
  where you want the host + runtime to live in one Python process.

Both return an :class:`InstalledHooks` you must ``.uninstall()`` on
shutdown (typically inside a ``try / finally``).

The bridge between OpenClaw events and the runtime is the same in
both modes — only the joinpoint sink changes (daemon over HTTP vs
local ``OpenCOATRuntime`` in-proc).

**The closed loop — events go in, advice comes out.**

``install_hooks`` subscribes to OpenClaw events and feeds each one
to the runtime. The runtime answers with a
:class:`opencoat_runtime_protocol.ConcernInjection` describing what
concerns matched and what advice rows to weave; that injection is
buffered onto :attr:`InstalledHooks.pending`. Hosts pick it up at the
two materialisation points OpenCOAT cares about:

.. code-block:: python

    installed = install(openclaw_host)
    try:
        while turn := openclaw_host.next_turn():
            # 1. fire events through the host as usual — install_hooks
            #    pushes each one into the daemon and buffers the result.
            turn.run_until_prompt()

            # 2. PROMPT FOLD — merge every buffered injection into the
            #    mutable prompt context BEFORE calling the LLM.
            turn.prompt_ctx = installed.apply_to(turn.prompt_ctx)

            # 3. TOOL DISPATCH — decode TOOL_GUARD advice for each
            #    pending tool call. ``None`` means default-allow.
            for call in turn.pending_tool_calls():
                outcome = installed.guard_tool_call(call)
                if outcome is not None and outcome.blocked:
                    turn.refuse(call, reason=outcome.block_reason)
                elif outcome is not None:
                    turn.dispatch(call["name"], outcome.arguments,
                                  notes=outcome.notes)
                else:
                    turn.dispatch(call["name"], call["arguments"])
    finally:
        installed.uninstall()

For a runnable single-file demo (no real OpenClaw needed — a tiny
:class:`OpenClawHost` fake is enough), see ``opencoat-skill``'s
``demo_host.py`` quickstart.
"""

from __future__ import annotations

import os
from typing import Any

from opencoat_runtime_core import OpenCOATRuntime, RuntimeConfig
from opencoat_runtime_core.llm import StubLLMClient
from opencoat_runtime_host_openclaw import (
    InstalledHooks,
    OpenClawAdapter,
    OpenClawHost,
    OpenClawMemoryBridge,
    install_hooks,
)
from opencoat_runtime_host_sdk import Client
from opencoat_runtime_protocol import ConcernInjection, JoinpointEvent
from opencoat_runtime_storage.memory import MemoryConcernStore, MemoryDCNStore

from .concerns import seed_concerns

# OpenClaw events the adapter subscribes to by default. Kept narrow so
# the scaffold's seeded concerns reach reachable joinpoints (pinned by
# ``test_openclaw_concerns_reach_default_subscription``).
DEFAULT_EVENT_NAMES: tuple[str, ...] = (
    "agent.started",
    "agent.user_message",
    "agent.memory_write",
)

# Where ``install()`` looks for a running daemon. Override via the
# ``daemon_url=`` argument or the ``OPENCOAT_DAEMON_URL`` env var.
DEFAULT_DAEMON_URL = "http://127.0.0.1:7878"


class _DaemonRuntime:
    """Adapter wrapping a daemon :class:`Client` as a :class:`RuntimeLike`.

    :func:`install_hooks` only needs ``.on_joinpoint(jp, …)`` from the
    runtime, which maps cleanly onto :meth:`Client.emit`. Keep this
    tiny proxy in the scaffold so the seam between OpenClaw events
    and a remote runtime is obvious in user-editable code.
    """

    def __init__(self, client: Client) -> None:
        self._client = client

    @property
    def client(self) -> Client:
        return self._client

    def on_joinpoint(
        self,
        jp: JoinpointEvent,
        *,
        context: dict[str, Any] | None = None,
        return_none_when_empty: bool = False,
    ) -> ConcernInjection | None:
        return self._client.emit(
            jp,
            context=context,
            return_none_when_empty=return_none_when_empty,
        )


def daemon_client(url: str | None = None) -> Client:
    """Connect a :class:`Client` to a running OpenCOAT daemon.

    Resolution order for the URL:

    1. The ``url`` argument, if given.
    2. The ``OPENCOAT_DAEMON_URL`` environment variable.
    3. :data:`DEFAULT_DAEMON_URL` (``http://127.0.0.1:7878``).
    """
    resolved = url or os.environ.get("OPENCOAT_DAEMON_URL") or DEFAULT_DAEMON_URL
    return Client.connect(resolved)


def install(
    host: OpenClawHost,
    *,
    event_names: tuple[str, ...] = DEFAULT_EVENT_NAMES,
    daemon_url: str | None = None,
) -> InstalledHooks:
    """Subscribe OpenClawAdapter callbacks to ``host`` and forward to the daemon.

    Each subscribed event is mapped to a :class:`JoinpointEvent` and
    submitted over HTTP JSON-RPC to a running ``opencoat runtime up``
    daemon. The daemon owns its own DCN store, so no local
    :class:`OpenClawMemoryBridge` is wired here; memory-write events
    still flow through as joinpoints and the daemon-side runtime
    records them on its DCN.

    Caller must call ``.uninstall()`` on the returned handle (typically
    inside a ``try / finally``).
    """
    client = daemon_client(daemon_url)
    runtime = _DaemonRuntime(client)
    return install_hooks(
        host,
        runtime=runtime,
        adapter=OpenClawAdapter(),
        bridge=None,
        event_names=event_names,
    )


def build_runtime() -> OpenCOATRuntime:
    """Construct an in-process :class:`OpenCOATRuntime` (legacy path).

    Used by :func:`install_in_process`. Prefer :func:`install` for
    real deployments so concerns and DCN persist across host
    restarts and are visible to the ``opencoat`` CLI.
    """
    return OpenCOATRuntime(
        RuntimeConfig(),
        concern_store=MemoryConcernStore(),
        dcn_store=MemoryDCNStore(),
        llm=StubLLMClient(),
    )


def seed_stores(runtime: OpenCOATRuntime) -> None:
    """Seed a local in-process runtime with the scaffold's concerns."""
    for concern in seed_concerns():
        runtime.concern_store.upsert(concern)
        runtime.dcn_store.add_node(concern)


def install_in_process(
    host: OpenClawHost,
    *,
    event_names: tuple[str, ...] = DEFAULT_EVENT_NAMES,
) -> tuple[OpenCOATRuntime, InstalledHooks]:
    """Embedded-runtime install (one Python process, memory stores).

    Builds a fresh :class:`OpenCOATRuntime`, seeds it from
    :func:`seed_concerns`, and wires OpenClawAdapter +
    :class:`OpenClawMemoryBridge` against it. Returns ``(runtime,
    installed)`` so callers can introspect the local stores.

    Use when a daemon is overkill — unit tests, demos that fit in one
    process, or scripts where state lifetime equals process lifetime.
    """
    runtime = build_runtime()
    seed_stores(runtime)
    installed = install_hooks(
        host,
        runtime=runtime,
        adapter=OpenClawAdapter(),
        bridge=OpenClawMemoryBridge(dcn_store=runtime.dcn_store),
        event_names=event_names,
    )
    return runtime, installed


__all__ = [
    "DEFAULT_DAEMON_URL",
    "DEFAULT_EVENT_NAMES",
    "build_runtime",
    "daemon_client",
    "install",
    "install_in_process",
    "seed_stores",
]
