"""Optional host-adapter overrides for OpenClaw.

Generated by ``opencoat plugin install openclaw`` (post-M5 DX sprint).

The default :class:`OpenClawAdapter` shipped in
``opencoat_runtime_host_openclaw`` already implements the
:class:`HostAdapter` protocol end-to-end. Subclass it here only when
you need to customize event mapping, injection application, or tool
guard policy.
"""

from __future__ import annotations

from typing import Any

from opencoat_runtime_host_openclaw import OpenClawAdapter
from opencoat_runtime_host_openclaw.tool_guard import ToolGuardOutcome
from opencoat_runtime_protocol import ConcernInjection


class CustomOpenClawAdapter(OpenClawAdapter):
    """Drop-in adapter — override the methods below to taste."""

    @property
    def host_name(self) -> str:
        return "openclaw"

    def guard_tool_call(
        self,
        tool_call: dict[str, Any],
        injection: ConcernInjection,
    ) -> ToolGuardOutcome:
        # Wrap the parent decision with your own audit / metrics if
        # needed; the default path is the M5 tool_guard interpreter.
        return super().guard_tool_call(tool_call, injection)


__all__ = ["CustomOpenClawAdapter"]
