"""Bootstrap a user-defined host against the OpenCOAT runtime.

Generated by ``opencoat plugin install custom``.

Two install paths are exposed; pick the one that matches your topology:

* :func:`daemon_client` — **daemon-backed** (default). Returns a
  :class:`Client` connected to a long-running OpenCOAT daemon over
  HTTP JSON-RPC. Pair with::

      opencoat runtime up
      opencoat concern import --demo        # or your own concerns

  Drive your :class:`CustomHostAdapter` from your own agent loop and
  hand each :class:`JoinpointEvent` to ``client.emit(jp)``. Concerns
  + DCN state live in the daemon, so ``opencoat concern …`` /
  ``opencoat dcn …`` show the same picture your host agent reacts to.

* :func:`build_runtime_with_adapter` — embedded runtime, memory stores,
  stub LLM. No daemon needed. Useful for unit tests or scripts where
  host + runtime live in one process.
"""

from __future__ import annotations

import os

from opencoat_runtime_core import OpenCOATRuntime, RuntimeConfig
from opencoat_runtime_core.llm import StubLLMClient
from opencoat_runtime_host_sdk import Client
from opencoat_runtime_storage.memory import MemoryConcernStore, MemoryDCNStore

from .concerns import seed_concerns
from .host_adapter import CustomHostAdapter

# Where :func:`daemon_client` looks for a running daemon.
DEFAULT_DAEMON_URL = "http://127.0.0.1:7878"


def daemon_client(url: str | None = None) -> Client:
    """Connect a :class:`Client` to a running OpenCOAT daemon.

    Resolution order for the URL:

    1. The ``url`` argument, if given.
    2. The ``OPENCOAT_DAEMON_URL`` environment variable.
    3. :data:`DEFAULT_DAEMON_URL` (``http://127.0.0.1:7878``).

    Typical use::

        from .host_adapter import CustomHostAdapter

        client = daemon_client()
        adapter = CustomHostAdapter(host_name="my-framework")

        for event in my_agent.events:
            jp = adapter.map_host_event(event)
            if jp is None:
                continue
            injection = client.emit(jp)
            if injection is not None:
                adapter.apply_injection(injection, my_agent.context)
    """
    resolved = url or os.environ.get("OPENCOAT_DAEMON_URL") or DEFAULT_DAEMON_URL
    return Client.connect(resolved)


def build_runtime() -> OpenCOATRuntime:
    """Construct an in-process :class:`OpenCOATRuntime` (legacy path).

    Prefer :func:`daemon_client` for real deployments so concerns and
    DCN persist across host restarts and are visible to the
    ``opencoat`` CLI.
    """
    return OpenCOATRuntime(
        RuntimeConfig(),
        concern_store=MemoryConcernStore(),
        dcn_store=MemoryDCNStore(),
        llm=StubLLMClient(),
    )


def seed_stores(runtime: OpenCOATRuntime) -> None:
    """Seed an in-process runtime with the scaffold's concerns."""
    for concern in seed_concerns():
        runtime.concern_store.upsert(concern)
        runtime.dcn_store.add_node(concern)


def build_runtime_with_adapter(
    host_name: str = "custom",
) -> tuple[OpenCOATRuntime, CustomHostAdapter]:
    """Convenience helper for the in-process wiring (no daemon)."""
    runtime = build_runtime()
    seed_stores(runtime)
    return runtime, CustomHostAdapter(host_name=host_name)


__all__ = [
    "DEFAULT_DAEMON_URL",
    "build_runtime",
    "build_runtime_with_adapter",
    "daemon_client",
    "seed_stores",
]
